INSERT INTO facilities VALUES ('SQL', 'QLA');
INSERT INTO facilities VALUES ('ODBC', 'API');
INSERT INTO facilities VALUES ('LINQ', 'LIN');
INSERT INTO facilities VALUES ('Links', 'LIN');
INSERT INTO facilities VALUES ('Rails', 'ORM');
INSERT INTO facilities VALUES ('DSH', 'LIB');
INSERT INTO facilities VALUES ('ADO.NET', 'ORM');
INSERT INTO facilities VALUES ('Kleisli', 'QLA');
INSERT INTO facilities VALUES ('HaskellDB', 'LIB');

INSERT INTO features VALUES ('SQL', 'aval');
INSERT INTO features VALUES ('SQL', 'type');
INSERT INTO features VALUES ('SQL', 'SQL!');
INSERT INTO features VALUES ('LINQ', 'nest');
INSERT INTO features VALUES ('LINQ', 'comp');
INSERT INTO features VALUES ('LINQ', 'type');
INSERT INTO features VALUES ('Links', 'comp');
INSERT INTO features VALUES ('Links', 'type');
INSERT INTO features VALUES ('Links', 'SQL!');
INSERT INTO features VALUES ('Rails', 'nest');
INSERT INTO features VALUES ('Rails', 'maps');
INSERT INTO features VALUES ('DSH', 'list');
INSERT INTO features VALUES ('DSH', 'nest');
INSERT INTO features VALUES ('DSH', 'comp');
INSERT INTO features VALUES ('DSH', 'aval');
INSERT INTO features VALUES ('DSH', 'type');
INSERT INTO features VALUES ('DSH', 'SQL!');
INSERT INTO features VALUES ('ADO.NET', 'maps');
INSERT INTO features VALUES ('ADO.NET', 'comp');
INSERT INTO features VALUES ('ADO.NET', 'type');
INSERT INTO features VALUES ('Kleisli', 'list');
INSERT INTO features VALUES ('Kleisli', 'nest');
INSERT INTO features VALUES ('Kleisli', 'comp');
INSERT INTO features VALUES ('Kleisli', 'type');
INSERT INTO features VALUES ('HaskellDB', 'comp');
INSERT INTO features VALUES ('HaskellDB', 'type');
INSERT INTO features VALUES ('HaskellDB', 'SQL!');

INSERT INTO meanings VALUES ('list', 'respects list order');
INSERT INTO meanings VALUES ('nest', 'supports data nesting');
INSERT INTO meanings VALUES ('aval', 'avoid query avalanches');
INSERT INTO meanings VALUES ('type', 'is statically type-checked');
INSERT INTO meanings VALUES ('SQL!', 'guarantees translation to SQL');
INSERT INTO meanings VALUES ('maps', 'admits user-defined object mappings');
INSERT INTO meanings VALUES ('comp', 'has compositional syntax and semantics');